import { register, load } from '@horsecoder/flow';
import { loadMy } from './flows_my';
import { flowFilterWebsiteRichTextListByTypeFacade as websiteInformationFlowFilterWebsiteRichTextListByTypeFacade } from '@/flows/com.horsecoder.common.intelligentServiceEngineerLab.chinaInternetScienceConference.websiteInformation/FilterWebsiteRichTextListByType';
import websiteInformationFlowFilterWebsiteRichTextListByType from '@/flows/com.horsecoder.common.intelligentServiceEngineerLab.chinaInternetScienceConference.websiteInformation/FilterWebsiteRichTextListByType/flow.json';
import RelatedDownloadComponentOnClickOnRelevantDownloadLinkJumpFlowOnClickOnRelevantDownloadLinkJump from '@/components/RelatedDownloadComponent/flows/OnClickOnRelevantDownloadLinkJump/flow.json';
import { flowCodeOnClickOnRelevantDownloadLinkJump as RelatedDownloadComponentOnClickOnRelevantDownloadLinkJumpFlowCodeOnClickOnRelevantDownloadLinkJump } from '@/components/RelatedDownloadComponent/flows/OnClickOnRelevantDownloadLinkJump/codes/FlowCodeOnClickOnRelevantDownloadLinkJump';
import WebsiteHomepageOnInitializeRelatedDownloadListFlowOnInitializeRelatedDownloadList from '@/pages/WebsiteHomepage/flows/OnInitializeRelatedDownloadList/flow.json';
import { flowCodeOnInitializeRelatedDownloadList as WebsiteHomepageOnInitializeRelatedDownloadListFlowCodeOnInitializeRelatedDownloadList } from '@/pages/WebsiteHomepage/flows/OnInitializeRelatedDownloadList/codes/FlowCodeOnInitializeRelatedDownloadList';
import { flowCodeSetRelatedDownloadList as WebsiteHomepageOnInitializeRelatedDownloadListFlowCodeSetRelatedDownloadList } from '@/pages/WebsiteHomepage/flows/OnInitializeRelatedDownloadList/codes/FlowCodeSetRelatedDownloadList';
import GeneralLayoutOnHomeButtonClickFlowOnHomeButtonClick from '@/layouts/GeneralLayout/flows/OnHomeButtonClick/flow.json';
import { flowCodeOnHomeButtonClick as GeneralLayoutOnHomeButtonClickFlowCodeOnHomeButtonClick } from '@/layouts/GeneralLayout/flows/OnHomeButtonClick/codes/FlowCodeOnHomeButtonClick';
import GeneralLayoutOnJumpHomepageFlowOnJumpHomepage from '@/layouts/GeneralLayout/flows/OnJumpHomepage/flow.json';
import { flowCodeOnJumpHomepage as GeneralLayoutOnJumpHomepageFlowCodeOnJumpHomepage } from '@/layouts/GeneralLayout/flows/OnJumpHomepage/codes/FlowCodeOnJumpHomepage';
import WebsiteHomepageOnInitializeMeetingNotificationListFlowOnInitializeMeetingNotificationList from '@/pages/WebsiteHomepage/flows/OnInitializeMeetingNotificationList/flow.json';
import { flowCodeOnInitializeMeetingNotificationList as WebsiteHomepageOnInitializeMeetingNotificationListFlowCodeOnInitializeMeetingNotificationList } from '@/pages/WebsiteHomepage/flows/OnInitializeMeetingNotificationList/codes/FlowCodeOnInitializeMeetingNotificationList';
import { flowCodeSetMeetingNotificationList as WebsiteHomepageOnInitializeMeetingNotificationListFlowCodeSetMeetingNotificationList } from '@/pages/WebsiteHomepage/flows/OnInitializeMeetingNotificationList/codes/FlowCodeSetMeetingNotificationList';

export const loadAll = async () => {
  loadMy();
  register('@com.horsecoder.common.intelligentServiceEngineerLab.chinaInternetScienceConference.websiteInformation/FLOW_CODE_FILTER_WEBSITE_RICH_TEXT_LIST_BY_TYPE', websiteInformationFlowFilterWebsiteRichTextListByTypeFacade);
  load('@com.horsecoder.common.intelligentServiceEngineerLab.chinaInternetScienceConference.websiteInformation/FLOW_FILTER_WEBSITE_RICH_TEXT_LIST_BY_TYPE', JSON.parse(JSON.stringify(websiteInformationFlowFilterWebsiteRichTextListByType)))
  load('@com.horsecoder.common.intelligentServiceEngineerLab.chinaInternetScienceConference.umi.website/relatedDownloadComponent/FLOW_ON_CLICK_ON_RELEVANT_DOWNLOAD_LINK_JUMP', JSON.parse(JSON.stringify(RelatedDownloadComponentOnClickOnRelevantDownloadLinkJumpFlowOnClickOnRelevantDownloadLinkJump)))
  register('RelatedDownloadComponent/OnClickOnRelevantDownloadLinkJump/FLOW_CODE_ON_CLICK_ON_RELEVANT_DOWNLOAD_LINK_JUMP', RelatedDownloadComponentOnClickOnRelevantDownloadLinkJumpFlowCodeOnClickOnRelevantDownloadLinkJump);
  load('@com.horsecoder.common.intelligentServiceEngineerLab.chinaInternetScienceConference.umi.website/websiteHomepage/FLOW_ON_INITIALIZE_RELATED_DOWNLOAD_LIST', JSON.parse(JSON.stringify(WebsiteHomepageOnInitializeRelatedDownloadListFlowOnInitializeRelatedDownloadList)))
  register('WebsiteHomepage/OnInitializeRelatedDownloadList/FLOW_CODE_ON_INITIALIZE_RELATED_DOWNLOAD_LIST', WebsiteHomepageOnInitializeRelatedDownloadListFlowCodeOnInitializeRelatedDownloadList);
  register('WebsiteHomepage/OnInitializeRelatedDownloadList/FLOW_CODE_SET_RELATED_DOWNLOAD_LIST', WebsiteHomepageOnInitializeRelatedDownloadListFlowCodeSetRelatedDownloadList);
  load('@com.horsecoder.common.intelligentServiceEngineerLab.chinaInternetScienceConference.umi.website/generalLayout/FLOW_ON_HOME_BUTTON_CLICK', JSON.parse(JSON.stringify(GeneralLayoutOnHomeButtonClickFlowOnHomeButtonClick)))
  register('GeneralLayout/OnHomeButtonClick/FLOW_CODE_ON_HOME_BUTTON_CLICK', GeneralLayoutOnHomeButtonClickFlowCodeOnHomeButtonClick);
  load('@com.horsecoder.common.intelligentServiceEngineerLab.chinaInternetScienceConference.umi.website/generalLayout/FLOW_ON_JUMP_HOMEPAGE', JSON.parse(JSON.stringify(GeneralLayoutOnJumpHomepageFlowOnJumpHomepage)))
  register('GeneralLayout/OnJumpHomepage/FLOW_CODE_ON_JUMP_HOMEPAGE', GeneralLayoutOnJumpHomepageFlowCodeOnJumpHomepage);
  load('@com.horsecoder.common.intelligentServiceEngineerLab.chinaInternetScienceConference.umi.website/websiteHomepage/FLOW_ON_INITIALIZE_MEETING_NOTIFICATION_LIST', JSON.parse(JSON.stringify(WebsiteHomepageOnInitializeMeetingNotificationListFlowOnInitializeMeetingNotificationList)))
  register('WebsiteHomepage/OnInitializeMeetingNotificationList/FLOW_CODE_ON_INITIALIZE_MEETING_NOTIFICATION_LIST', WebsiteHomepageOnInitializeMeetingNotificationListFlowCodeOnInitializeMeetingNotificationList);
  register('WebsiteHomepage/OnInitializeMeetingNotificationList/FLOW_CODE_SET_MEETING_NOTIFICATION_LIST', WebsiteHomepageOnInitializeMeetingNotificationListFlowCodeSetMeetingNotificationList);
}
